#Modified from https://gist.github.com/zackwag/fa9ec457466f9980a0f19d7ad728db43, thanks zackwag.

blueprint:
  name: Hue Tap Button Actions
  description: |
    This blueprint triggers a user-specified action when a button on a Hue Tap is pressed.
  domain: automation
  input:
    hue_tap:
      name: Hue Tap
      description: "The Hue Tap that triggers actions"
      selector:
        device:
          integration: mqtt
          model: Hue tap (8718696743133)

    button_1_action:
      name: First Button Action
      description: "The action to execute when the first button is pressed."
      default: []
      selector:
        action: {}

    button_2_action:
      name: Second Button Action
      description: "The action to execute when the second button is pressed."
      default: []
      selector:
        action: {}

    button_3_action:
      name: Third Button Action
      description: "The action to execute when the third button is pressed."
      default: []
      selector:
        action: {}

    button_4_action:
      name: Fourth Button Action
      description: "The action to execute when the fourth button is pressed."
      default: []
      selector:
        action: {}

trigger:
- platform: device
  device_id: !input hue_tap
  domain: mqtt
  type: action
  subtype: press_1
- platform: device
  device_id: !input hue_tap
  domain: mqtt
  type: action
  subtype: press_2
- platform: device
  device_id: !input hue_tap
  domain: mqtt
  type: action
  subtype: press_3
- platform: device
  device_id: !input hue_tap
  domain: mqtt
  type: action
  subtype: press_4

condition: []

action:
  - choose:
      - conditions: '{{ trigger.event.data.subtype == press_1 }}'
        sequence: !input button_1_action
      - conditions: '{{ trigger.event.data.subtype == press_2 }}'
        sequence: !input button_2_action
      - conditions: '{{ trigger.event.data.subtype == press_3 }}'
        sequence: !input button_3_action
      - conditions: '{{ trigger.event.data.subtype == press_4 }}'
        sequence: !input button_4_action